import mongoose from "mongoose";
import dotenv from "dotenv";
import Book from "../models/Book.js";
import Category from "../models/Category.js";
import User from "../models/User.js";

dotenv.config();

const seedBooks = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected");

    await Book.deleteMany();
    await Category.deleteMany();
    await User.deleteMany();

    // Create admin
    const admin = await User.create({
      name: "Admin",
      email: "admin@example.com",
      password: "12345678", // must be hashed via pre-save hook
      role: "admin",
    });

    // Create categories
    const categories = await Category.insertMany([
      { name: "Fiction", isActive: true },
      { name: "Science", isActive: true },
      { name: "History", isActive: true },
      { name: "Self-Help", isActive: true },
      { name: "Fantasy", isActive: true },
      { name: "Mystery", isActive: true },
    ]);

const books = [
  /* ================= FICTION ================= */
  {
    title: "To Kill a Mockingbird",
    slug: "to-kill-a-mockingbird",
    author: "Harper Lee",
    description: "A novel about racial injustice and moral growth.",
    price: 399,
    discountPrice: 299,
    category: categories[0]._id,
    stock: 40,
    rating: 4.8,
    totalReviews: 520,
    image: { public_id: "mockingbird", url: "/uploads/mockingbird.png"},
  },
  {
    title: "The Catcher in the Rye",
    slug: "the-catcher-in-the-rye",
    author: "J.D. Salinger",
    description: "A story of teenage rebellion and identity.",
    price: 349,
    category: categories[0]._id,
    stock: 30,
    rating: 4.2,
    image: { public_id: "catcher", url: "/uploads/catchereye.png" },
  },
  {
    title: "The Great Gatsby",
    slug: "the-great-gatsby",
    author: "F. Scott Fitzgerald",
    description: "A tragic story of love and ambition.",
    price: 299,
    discountPrice: 199,
    category: categories[0]._id,
    stock: 50,
    rating: 4.5,
    isFeatured: true,
    image: { public_id: "gatsby", url: "/uploads/greatgatsby.png" },
  },
  {
    title: "Pride and Prejudice",
    slug: "pride-and-prejudice",
    author: "Jane Austen",
    description: "A romantic novel of manners.",
    price: 349,
    category: categories[0]._id,
    stock: 35,
    rating: 4.6,
    image: { public_id: "pride", url: "/uploads/prideandprejudice.png" },
  },
  {
    title: "Of Mice and Men",
    slug: "of-mice-and-men",
    author: "John Steinbeck",
    description: "A tale of friendship and dreams.",
    price: 299,
    category: categories[0]._id,
    stock: 28,
    rating: 4.3,
    image: { public_id: "mice", url: "/uploads/miceandmen.png" },
  },
  {
    title: "The Old Man and the Sea",
    slug: "the-old-man-and-the-sea",
    author: "Ernest Hemingway",
    description: "A story of perseverance and pride.",
    price: 249,
    category: categories[0]._id,
    stock: 32,
    rating: 4.4,
    image: { public_id: "oldman", url: "/uploads/oldmanandsea.png" },
  },

  /* ================= SCIENCE ================= */
  {
    title: "A Brief History of Time",
    slug: "a-brief-history-of-time",
    author: "Stephen Hawking",
    description: "From the Big Bang to black holes.",
    price: 599,
    discountPrice: 499,
    category: categories[1]._id,
    stock: 25,
    rating: 4.6,
    isBestSeller: true,
    image: { public_id: "time", url: "/uploads/historyoftime.png" },
  },
  {
    title: "The Selfish Gene",
    slug: "the-selfish-gene",
    author: "Richard Dawkins",
    description: "Evolutionary biology explained.",
    price: 549,
    category: categories[1]._id,
    stock: 20,
    rating: 4.5,
    image: { public_id: "gene", url: "/uploads/selfishgene.png" },
  },
  {
    title: "Cosmos",
    slug: "cosmos",
    author: "Carl Sagan",
    description: "Exploring the universe.",
    price: 499,
    category: categories[1]._id,
    stock: 30,
    rating: 4.7,
    image: { public_id: "cosmos", url: "/uploads/cosmos.png" },
  },
  {
    title: "Astrophysics for People in a Hurry",
    slug: "astrophysics-for-people-in-a-hurry",
    author: "Neil deGrasse Tyson",
    description: "Quick guide to the universe.",
    price: 399,
    category: categories[1]._id,
    stock: 27,
    rating: 4.4,
    image: { public_id: "astro", url: "/uploads/astrophysics.jpg"},
  },
  {
    title: "The Elegant Universe",
    slug: "the-elegant-universe",
    author: "Brian Greene",
    description: "Superstrings and space-time.",
    price: 599,
    category: categories[1]._id,
    stock: 18,
    rating: 4.3,
    image: { public_id: "elegant", url: "/uploads/elegantuniverse.png" },
  },
  {
    title: "Surely You're Joking, Mr. Feynman!",
    slug: "surely-youre-joking-mr-feynman",
    author: "Richard Feynman",
    description: "Adventures of a curious physicist.",
    price: 449,
    category: categories[1]._id,
    stock: 22,
    rating: 4.6,
    image: { public_id: "feynman", url: "/uploads/jokingfeyman.png" },
  },

  /* ================= HISTORY ================= */
  {
    title: "Sapiens",
    slug: "sapiens",
    author: "Yuval Noah Harari",
    description: "A brief history of humankind.",
    price: 699,
    discountPrice: 599,
    category: categories[2]._id,
    stock: 35,
    rating: 4.8,
    isBestSeller: true,
    image: { public_id: "sapiens", url: "/upload/sapiens.png" },
  },
  {
    title: "Homo Deus",
    slug: "homo-deus",
    author: "Yuval Noah Harari",
    description: "A brief history of tomorrow.",
    price: 699,
    category: categories[2]._id,
    stock: 28,
    rating: 4.6,
    image: { public_id: "homodeus", url: "/upload/homodeus.png" },
  },
  {
    title: "Guns, Germs, and Steel",
    slug: "guns-germs-and-steel",
    author: "Jared Diamond",
    description: "Factors shaping human history.",
    price: 649,
    category: categories[2]._id,
    stock: 24,
    rating: 4.5,
    image: { public_id: "guns", url: "/upload/gunsgerms.png" },
  },
  {
    title: "The Silk Roads",
    slug: "the-silk-roads",
    author: "Peter Frankopan",
    description: "A new history of the world.",
    price: 599,
    category: categories[2]._id,
    stock: 21,
    rating: 4.4,
    image: { public_id: "silk", url: "/uploads/silkroads.png" },
  },
  {
    title: "SPQR",
    slug: "spqr",
    author: "Mary Beard",
    description: "History of ancient Rome.",
    price: 549,
    category: categories[2]._id,
    stock: 19,
    rating: 4.3,
    image: { public_id: "spqr", url: "/upload/spqr.png" },
  },
  {
    title: "Team of Rivals",
    slug: "team-of-rivals",
    author: "Doris Kearns Goodwin",
    description: "Political genius of Abraham Lincoln.",
    price: 599,
    category: categories[2]._id,
    stock: 20,
    rating: 4.6,
    image: { public_id: "rivals", url: "/upload/teamofrivals.png" },
  },

  /* ================= SELF-HELP ================= */
  {
    title: "Atomic Habits",
    slug: "atomic-habits",
    author: "James Clear",
    description: "Build good habits, break bad ones.",
    price: 499,
    discountPrice: 399,
    category: categories[3]._id,
    stock: 60,
    rating: 4.8,
    isBestSeller: true,
    image: { public_id: "atomic", url: "/upload/atomichabits.png" },
  },
  {
    title: "The Power of Now",
    slug: "the-power-of-now",
    author: "Eckhart Tolle",
    description: "Living in the present moment.",
    price: 449,
    category: categories[3]._id,
    stock: 45,
    rating: 4.6,
    image: { public_id: "now", url: "/upload/powerofnow.png" },
  },
  {
    title: "Think Like a Monk",
    slug: "think-like-a-monk",
    author: "Jay Shetty",
    description: "Train your mind for peace.",
    price: 399,
    category: categories[3]._id,
    stock: 40,
    rating: 4.5,
    image: { public_id: "monk", url: "/upload/thinklikeamonk.png" },
  },
  {
    title: "Can't Hurt Me",
    slug: "cant-hurt-me",
    author: "David Goggins",
    description: "Master your mind.",
    price: 499,
    category: categories[3]._id,
    stock: 35,
    rating: 4.7,
    image: { public_id: "goggins", url: "/upload/canthurtme.png" },
  },
  {
    title: "The 5 AM Club",
    slug: "the-5-am-club",
    author: "Robin Sharma",
    description: "Own your morning.",
    price: 399,
    category: categories[3]._id,
    stock: 38,
    rating: 4.4,
    image: { public_id: "5am", url: "/upload/5amclub.png" },
  },
  {
    title: "Ikigai",
    slug: "ikigai",
    author: "Hector Garcia",
    description: "The Japanese secret to long life.",
    price: 349,
    category: categories[3]._id,
    stock: 42,
    rating: 4.5,
    image: { public_id: "ikigai", url: "/upload/ikigai.png" },
  },

  /* ================= FANTASY ================= */
  {
    title: "The Hobbit",
    slug: "the-hobbit",
    author: "J.R.R. Tolkien",
    description: "A fantasy adventure.",
    price: 499,
    category: categories[4]._id,
    stock: 50,
    rating: 4.8,
    image: { public_id: "hobbit", url: "/upload/hobbit.png" },
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    slug: "harry-potter-1",
    author: "J.K. Rowling",
    description: "The beginning of a magical journey.",
    price: 499,
    category: categories[4]._id,
    stock: 60,
    rating: 4.9,
    image: { public_id: "hp1", url: "/upload/harrypotter.png" },
  },
  {
    title: "The Name of the Wind",
    slug: "the-name-of-the-wind",
    author: "Patrick Rothfuss",
    description: "A legendary fantasy tale.",
    price: 549,
    category: categories[4]._id,
    stock: 28,
    rating: 4.7,
    image: { public_id: "wind", url: "/upload/nameofthewind.png" },
  },
  {
    title: "Mistborn",
    slug: "mistborn",
    author: "Brandon Sanderson",
    description: "Epic fantasy with unique magic.",
    price: 499,
    category: categories[4]._id,
    stock: 30,
    rating: 4.6,
    image: { public_id: "mistborn", url: "/upload/mistborn.jpg" },
  },
  {
    title: "The Way of Kings",
    slug: "the-way-of-kings",
    author: "Brandon Sanderson",
    description: "An epic high fantasy.",
    price: 699,
    category: categories[4]._id,
    stock: 22,
    rating: 4.8,
    image: { public_id: "kings", url: "/upload/wayofkings.jpg" },
  },
  {
    title: "Eragon",
    slug: "eragon",
    author: "Christopher Paolini",
    description: "A dragon rider's journey.",
    price: 399,
    category: categories[4]._id,
    stock: 35,
    rating: 4.4,
    image: { public_id: "eragon", url: "/upload/eragon.png" },
  },

  /* ================= MYSTERY ================= */
  {
    title: "The Da Vinci Code",
    slug: "the-da-vinci-code",
    author: "Dan Brown",
    description: "A thrilling mystery.",
    price: 499,
    category: categories[5]._id,
    stock: 45,
    rating: 4.3,
    image: { public_id: "davinci", url: "/upload/davincicode.png" },
  },
  {
    title: "Gone Girl",
    slug: "gone-girl",
    author: "Gillian Flynn",
    description: "A psychological thriller.",
    price: 399,
    category: categories[5]._id,
    stock: 32,
    rating: 4.4,
    image: { public_id: "gonegirl", url: "/upload/gonegirl.png" },
  },
  {
    title: "The Girl with the Dragon Tattoo",
    slug: "the-girl-with-the-dragon-tattoo",
    author: "Stieg Larsson",
    description: "A dark mystery novel.",
    price: 449,
    category: categories[5]._id,
    stock: 27,
    rating: 4.5,
    image: { public_id: "dragon", url: "/upload/girlwithdragon.png" },
  },
  {
    title: "Big Little Lies",
    slug: "big-little-lies",
    author: "Liane Moriarty",
    description: "Secrets beneath perfect lives.",
    price: 399,
    category: categories[5]._id,
    stock: 29,
    rating: 4.3,
    image: { public_id: "lies", url: "/upload/biglittlelies.png" },
  },
  {
    title: "The Silent Patient",
    slug: "the-silent-patient",
    author: "Alex Michaelides",
    description: "A shocking psychological mystery.",
    price: 449,
    category: categories[5]._id,
    stock: 31,
    rating: 4.6,
    image: { public_id: "silent", url: "/upload/silentpatient.png" },
  },
  {
    title: "Sherlock Holmes: The Hound of the Baskervilles",
    slug: "hound-of-the-baskervilles",
    author: "Arthur Conan Doyle",
    description: "A classic Sherlock Holmes mystery.",
    price: 349,
    category: categories[5]._id,
    stock: 34,
    rating: 4.7,
    image: { public_id: "sherlock", url: "/upload/sherlockholmes.png" },
  },
];

await Book.insertMany(
  books.map((book) => ({
    ...book,
    createdBy: admin._id,
  }))
);
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

seedBooks();

// to run the seeBooks 
// node src/scripts/seedBooks.js